version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: langchain-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: langchain_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: langchain_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
